### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by ghost** [eXpl0it3r/bnkextr#1]
I definitely don't know a lot about all of this stuff but here's the dilemma I have currently. I was able to get into the files of a PS3 game (Warhawk) and I found that some of the sound files are in ".bnk" files. I've looked up how to get the sounds out of there, and apparently bnkextr works but it doesn't seem to do anything for these files. Maybe it's because it's a PS3 game that I've opened up? Maybe I'm a noob? Not sure. Any ideas on what I can do?

**Comment by eXpl0it3r** [comment]
What steps did you exactly do? What does "it doesn't seem to do anything for these files" mean exactly?

Could you share one if the bnk files?

**Comment by kynmarch** [comment]
Dear eXpl0it3r

I believe I am having a similar issue.  I have attached a .zip file of the .bnk file (as I could not upload the .bnk file directly).

[job_esc_overpass.1.zip](https://github.com/eXpl0it3r/bnkextr/files/190893/job_esc_overpass.1.zip)

I have tried the following with the 1.0 and 1.1 versions of your bnkextr.exe 
- have the .bnk file and bnkextr.exe in the same folder, drag the .bnk file onto bnkextr.exe. A command prompt pops up for less that one second, and no extracted files can be found in the folder containing bnkextr.exe.
- gone into command prompt and tried entering "bnkextr.exe job_esc_overpass.1.bnk [/swap]" where the following text can be seen
  Wwise *.BNK File Extractor
  <c> CTPAX-X Team 2009-2010 - http://CTPAX-X.org
  <c> RAWR 2015 - http://rawr4firefall.com
  and no extracted files can be found in the folder containing bnkextr.exe.

I have tried a few other things in command prompt (which I cannot remember the exact details of what I did), but do I need to use the .cpp or .dpr files to alter the bnkextr.exe?!?

I would be grateful for any advice given and for your consideration of time.

Best Regards,
Kynmarch

**Comment by eXpl0it3r** [comment]
Hey @kynmarch 

Thanks for reaching out. The BNK format can contain various things. Ranging from sound files to sound settings or effects. The file you uploaded doesn't contain any sound files, which is why nothing gets extracted. In my experience most tiny BNK files (few KiB) don't contain any sound files.

If you have problems with other files as well, let me know. :smiley: 

@frakthegods If you need any further help, let me know. Otherwise I'll be closing this issue.

**Comment by eXpl0it3r** [comment]
Feel free to [contact me](https://my-gate.net/contact/) if you have any further questions.

**Comment by halloweeks** [comment]
I
