### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ItsBrank** [eXpl0it3r/bnkextr#10]
What license is this repo under, MIT, GNU...? Asking because of the `(c) RAWR 2015-2021 - https://rawr4firefall.com` string you print to cout.

**Comment by eXpl0it3r** [comment]
Looks like I didn't clarify this way back when I created the repo.

I've just added a [LICENSE.md](https://github.com/eXpl0it3r/bnkextr/blob/master/LICENSE.md) which puts the C++ code under either Public Domain or MIT

**Comment by ItsBrank** [comment]
Thanks yo.
