### ISSUE TITLE
Typo in EventActionType

### ISSUE THREAD

**Issue by awsr** [eXpl0it3r/bnkextr#13]
Am I correct in assuming that the following is meant to be `SetVoiceVolume`?
https://github.com/eXpl0it3r/bnkextr/blob/e151cf733655564244aaf5a698f8859f9342abf1/bnkextr.cpp#L98

**Comment by eXpl0it3r** [comment]
Yeah, that looks like a typo. Thanks for the report!

**Comment by eXpl0it3r** [comment]
Fixed with 24ffc51cffee630a2a3e3efd58a720f615f37edf
