### ISSUE TITLE
Kaitai Struct Specification Incompletedness

### ISSUE THREAD

**Issue by abheekda1** [eXpl0it3r/bnkextr#14]
What exactly's missing from it as is said in the README? I'd be happy to take a look and see if I can improve on it because I think it would be really cool to generate parsers for different languages, and namely for my own project [here](https://github.com/WolvenKit/wwise-audio-tools).

Thanks for this tool!

**Comment by abheekda1** [comment]
Quick update on this:

I found a few exceptions where this definition doesn't quite work. I wrote down the exceptions in my own script [here](https://github.com/WolvenKit/wwise-audio-tools/blob/e88c6a0d5a270aab24db3ff6d9ad74324fb1efa3/src/main.cpp#L203-L207):
```cpp
if (file->name().find("music_") != std::string::npos ||
    file->name().find("vo_") != std::string::npos ||
    file->name().find("qu_") != std::string::npos ||
    file->name().find("mutations_") != std::string::npos) {
  continue;
}
```

**Comment by eXpl0it3r** [comment]
It's mostly that I gave up toying with Kaitai Script because I was going back to the 010 Templates, which I already had more information figured out and found it easier to specify things. Unfortunately, I don't remember where exactly I stopped.

I'd happy merge any improvements you make 🙂

**Comment by abheekda1** [comment]
No problem! I'll take a look and give it my best shot. I wonder if it has anything to do with the size of the offsets vary between `long` and `long long` depending on the version.

**Comment by abheekda1** [comment]
Actually it seems that instead of DIDX section, music and some other bnk types have an HIRC section? Not sure why.

**Comment by abheekda1** [comment]
Alright, so I've been working on this for a while and I've written a spec from the ground up with more header type support, if you'd like to add or link it in this repository, you can find it [here](https://github.com/WolvenKit/wwise-audio-tools/blob/feat/bnk-tools/ksy/bnk.ksy).

**Comment by eXpl0it3r** [comment]
Done: 61e6cad9ba3e00aa5e3fd902271515932bb5388f

Thanks for mentioning it here 🙂
