### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by SirStupidity** [eXpl0it3r/bnkextr#15]
How do I use this?

**Comment by eXpl0it3r** [comment]
As mentioned in the ReadMe:

```
Usage: bnkextr filename.bnk [/swap] [/nodir] [/obj]
        /swap - swap byte order (use it for unpacking 'Army of Two')
        /nodir - create no additional directory for the *.wem files
        /obj - generate an objects.txt file with the extracted object data
```

**Comment by SirStupidity** [comment]
> As mentioned in the ReadMe:
> 
> ```
> Usage: bnkextr filename.bnk [/swap] [/nodir] [/obj]
>         /swap - swap byte order (use it for unpacking 'Army of Two')
>         /nodir - create no additional directory for the *.wem files
>         /obj - generate an objects.txt file with the extracted object data
> ```

Do I put this in the terminal/cmd application?

**Comment by eXpl0it3r** [comment]
Yes
