### ISSUE TITLE
I am not able to compile it

### ISSUE THREAD

**Issue by krishkat** [eXpl0it3r/bnkextr#2]
When I try to compile the .cpp file with g++ from MINgw I get a hell of  a lot errors

**Comment by eXpl0it3r** [comment]
And the errors would be...?

**Comment by krishkat** [comment]
I found the error an .dll was missing

**Comment by eXpl0it3r** [comment]
If you use the `static` flag with MinGW (as shown in the readme) you don't really need any additional DLL.
