### ISSUE TITLE
is there any way to repack it for replacing the sound resources?

### ISSUE THREAD

**Issue by AlseinX** [eXpl0it3r/bnkextr#3]
I am trying to replace the champion sound effect in League Of Legends and I found many ways to unpack the wwise bnk files but still no way to repack them with replacement sound files.
So, is there any way to repack? Thank you very much.

**Comment by eXpl0it3r** [comment]
I have no experience with League Of Legends, but for some other game it was possible to replace the audio, as long as you used the same amount of bytes. Longer audio tracks won't work and for shorter ones you just have to fill it up with 0x00.

However, I don't think there's a tool that actually supports this, so if you want to achieve it, you'll have to edit files manually or write your own tool for it.

**Comment by AlseinX** [comment]
thank you very much anyway
