### ISSUE TITLE
bnkextr not actually extracting

### ISSUE THREAD

**Issue by KeZRoN** [eXpl0it3r/bnkextr#4]
I tried extracting sounds from DOOM 2016, but when I dragged the .bnk file to bnkextr.exe it popped up for a split second, closed, and nothing was extracted

**Comment by eXpl0it3r** [comment]
Dragging the file onto the exe is not how you're supposed to use it. Check the README.

**Comment by KeZRoN** [comment]
I've seen like, 12 tutorials that say that's how ya do it, good job internet

**Comment by eXpl0it3r** [comment]
Maybe it works with the original bnkextr. This is just a rewrite in C++ instead of Delphi with some fixes.
