### ISSUE TITLE
Can not open .exe

### ISSUE THREAD

**Issue by 1krad** [eXpl0it3r/bnkextr#8]
I am new to this so am not sure if I did something wrong. After cloning to Visual Studio, I selected the CPP file, and used the build current document button to create the .exe file, however the bnkextr.exe file crashes instantly every time I try to open it.

**Comment by eXpl0it3r** [comment]
What's the call stack when it crashes? And how do you know it crashes?

**Comment by 1krad** [comment]
After trying to view bnkextr.exe in visual studio, it seems that none of the code transferred at all. The .exe is completely blank. The cpp displays correctly and seems to have all the correct code. Is there some step I missed when building from the .cpp?

**Comment by eXpl0it3r** [comment]
If you use CMake see the steps in the README.
if you directly want to use Visual Studio:

- Create an Empty Project
- In the Solution view "Add existing file..."
- Open the cpp file
- Compile
- Run

If you just open the file without as adding it to your project, it won't get built.

**Comment by eXpl0it3r** [comment]
Were you able to build it, @1krad?
