### ISSUE TITLE
Baldur'sGate 3 sounds banks extract not working

### ISSUE THREAD

**Issue by pgmillon** [eXpl0it3r/bnkextr#9]
Hi,
I'm trying to extract the spells audio from BG3 bnk files using this tools with no luck.
I don't have any output to provide since there's none:

```
H:\Downloads\UnpackedData\SharedSoundBanks\Public\Shared\Assets\Sound>\Downloads\bnkextr.exe SPELLS.bnk
Wwise *.BNK File Extractor
(c) CTPAX-X Team 2009-2010 - http://www.CTPAX-X.org
(c) RAWR 2015 - http://www.rawr4firefall.com


H:\Downloads\UnpackedData\SharedSoundBanks\Public\Shared\Assets\Sound>
```

**Comment by eXpl0it3r** [comment]
Not all BNK files need to contain audio data, so might well be that SPELLS.bnk only contains effects instructions and whatever else WWISE allows to put in there.

If you [DM](https://twitter.com/DarkCisum) me the file, I'd take a look at it.

Alternatively, you can also check out other/more advanced tools in this region.

- [wwiser](https://github.com/bnnm/wwiser)
- [vgmstream](https://github.com/vgmstream/vgmstream)
- [Ravioli Game Tools](http://www.scampers.org/steve/sms/other.htm)

**Comment by eXpl0it3r** [comment]
@pgmillon Any update on this?
